// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbqe7Q2F65nRaKLLgQs7u0dyb51EEuKo',
    appId: '1:908650001854:web:714c3eb076c042508375ef',
    messagingSenderId: '908650001854',
    projectId: 'chat-ui-697ea',
    authDomain: 'chat-ui-697ea.firebaseapp.com',
    storageBucket: 'chat-ui-697ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNPSjr5TEiJAfZ4OJsfBY9koEq8ZlzXsE',
    appId: '1:908650001854:android:a21b7ecbc250ab8c8375ef',
    messagingSenderId: '908650001854',
    projectId: 'chat-ui-697ea',
    storageBucket: 'chat-ui-697ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhhBD0paOn54e356q7-WbdI9F0_1nV-o4',
    appId: '1:908650001854:ios:6b7389659add84b48375ef',
    messagingSenderId: '908650001854',
    projectId: 'chat-ui-697ea',
    storageBucket: 'chat-ui-697ea.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
